#!/bin/sh
# gen-embbuild-manifest.sh — emit the EmbBuild manifest that builds EmbCC ON
# EmbLinkOS (ROADMAP M4: "the OS builds the compiler that builds the OS's
# programs"). EmbBuild is a typed-manifest walker (myos docs/BUILD.md): each
# target is `name/kind/inputs/args/output`, each recipe one spawn.
#
# The manifest is GENERATED, not hand-written, on purpose. BUILD.md §6 records
# the format's real cost: a hand-listed `inputs:` header set silently goes
# stale when the include graph grows, and staleness detection then misses an
# edit. So the header closure of every unit is DERIVED here (cc -MM), exactly
# what §6 argues for. Re-run this whenever the sources or their includes change.
#
# Paths are the on-OS layout (docs/developer/selfhost-on-os.md): sources under
# /data/src/embcc (the src/ prefix dropped, subdirs preserved), EmbCC's own
# freestanding headers at /data/apps/embcc/include, newlib's ABI headers at
# /system/abi/include, the ABI objects at /system/abi, outputs staged under
# /data/build/out/embcc (EmbBuild NEVER writes /system — BUILD.md §3).
#
#   usage: tools/gen-embbuild-manifest.sh > build.ebm
#   env:   NEWLIB_INC  host newlib include dir (to compute the closure)
set -eu

cd "$(dirname "$0")/.."
. "$(dirname "$0")/hostpaths.sh"
NEWLIB_INC=${NEWLIB_INC:-$X86_NEWLIB/include}

# On-OS roots.
SRCROOT=/data/src/embcc
INCEMB=/data/apps/embcc/include
INCABI=/system/abi/include
OUTDIR=/data/build/out/embcc
ABI=/system/abi

# EmbCC's own translation units — the self-host source set (tests/golden/
# self-host.sh). Taken from the Makefile's SRCS, not restated: a hand-kept
# copy went stale the moment the aarch64 backend added sources.
SRCS=$(make -pn 2>/dev/null | sed -n 's/^SRCS := //p' | head -1)
[ -n "$SRCS" ] || { echo "gen-embbuild-manifest: cannot read SRCS from the Makefile" >&2; exit 1; }
# ...and the one unit that is not under src/ (see the Makefile), read
# the same way rather than restated, for the same reason.
SRCS_TOOLCORE=$(make -pn 2>/dev/null | sed -n 's/^SRCS_TOOLCORE := //p' | head -1)
TOOLCORE_CFLAGS=$(make -pn 2>/dev/null | \
                  sed -n 's/^TOOLCORE_CFLAGS := //p' | head -1)

# Map a host path to its on-OS path — or to nothing. A path under none of the
# three roots is a HOST artifact of the dependency scan (macOS clang adds its
# SDK's SDKSettings.json to every closure) and does not exist on the OS, so it
# must not become a manifest input.
mappath() {
    case "$1" in
        include/*)        echo "$INCEMB/${1#include/}" ;;
        src/*)            echo "$SRCROOT/${1#src/}" ;;
        # The units outside src/: the EMBX hash and .embdbg writer that
        # src/link/link.c calls. They keep their tools/ path under the
        # source root, so the mapping reverses unambiguously -- the
        # host runner (tools/embbuild-run.sh) turns it back. */
        tools/*)          echo "$SRCROOT/tools/${1#tools/}" ;;
        "$NEWLIB_INC"/*)  echo "$INCABI/${1#"$NEWLIB_INC"/}" ;;
        *)                : ;;
    esac
}

# Resolve `dir/../` segments. Portable on purpose: `realpath --relative-to`
# is GNU-only, and without it the Mac kept `codegen/../asm/emit.h` forms.
normpath() {
    p=$1
    while :; do
        q=$(printf '%s' "$p" | sed -e 's|/\./|/|g' -e 's|[^/][^/]*/\.\./||')
        [ "$q" = "$p" ] && break
        p=$q
    done
    printf '%s' "$p"
}

printf '# /data/src/embcc/build.ebm -- EmbBuild builds EmbCC, on the OS (ROADMAP M4).\n'
printf '# GENERATED by tools/gen-embbuild-manifest.sh -- do not hand-edit; header\n'
printf '# closures are derived (BUILD.md 6). The total loop: embcc builds embcc,\n'
printf '# embld links it, all from /data/src on the metal.\n\n'
printf 'project: embcc\n\n'

objs=""
for src in $SRCS $SRCS_TOOLCORE; do
    case $src in
        tools/*) rel=${src#tools/}; extra=$TOOLCORE_CFLAGS ;;
        *)       rel=${src#src/};   extra= ;;
    esac
    obj=$(echo "$rel" | tr / _); obj=${obj%.c}.o

    # Header closure: cc -MM, strip the `target:` and line-continuations, then
    # normalise each dep (resolve `..`) and map to its on-OS path.
    inputs=$(mappath "$src")
    deps=$(cc -MM -Iinclude -I"$NEWLIB_INC" "$src" 2>/dev/null \
           | sed 's/^[^:]*://; s/\\//g')
    for d in $deps; do
        [ "$d" = "$src" ] && continue
        m=$(mappath "$(normpath "$d")")
        [ -n "$m" ] && inputs="$inputs $m"
    done

    # A header pulled through several paths appears once (order preserved).
    inputs=$(printf '%s\n' $inputs | awk '!seen[$0]++' | tr '\n' ' ')
    printf 'name: %s\n' "$obj"
    printf 'kind: compile\n'
    printf 'inputs: %s\n' "$inputs"
    printf 'args: /data/apps/embcc/embcc.elf -c -I%s -I%s%s %s -o %s/%s\n' \
           "$INCEMB" "$INCABI" "${extra:+ $extra}" \
           "$(mappath "$src")" "$OUTDIR" "$obj"
    printf 'output: %s/%s\n\n' "$OUTDIR" "$obj"
    objs="$objs $OUTDIR/$obj"
done

# The link: crt0 + syscalls + every object + libc, exactly the self-host line
# (tests/golden/x86_64/self-host.sh), through EmbLD.
printf 'name: embcc.elf\n'
printf 'kind: link\n'
printf 'inputs: %s/crt0.o %s/syscalls.o%s %s/libc.a\n' "$ABI" "$ABI" "$objs" "$ABI"
printf 'args: /data/apps/embld/embld.elf -o %s/embcc.elf %s/crt0.o %s/syscalls.o%s %s/libc.a\n' \
       "$OUTDIR" "$ABI" "$ABI" "$objs" "$ABI"
printf 'output: %s/embcc.elf\n' "$OUTDIR"
