#!/bin/sh
# gen-kernel-manifest.sh — emit the EmbBuild manifest that builds the EmbLinkOS
# KERNEL on the OS (myos docs/BUILD.md §12, KM1: "EmbBuild rebuilds the kernel").
# The blockers §12.3 named are now cleared elsewhere: G1 (an on-OS assembler) is
# EmbAS/A1 — embcc -c dispatches the 6 .asm — and G2 (kernel_end) is EmbLD's L1.
# What §12.3 still needs is G5, this generator.
#
# Same shape as gen-embbuild-manifest.sh: a target per unit, header closures
# DERIVED (cc -MM), on-OS paths. A C compile per KERNEL_SRC unit (165 today)
# + 6 asm compiles + one link. /data/src mirrors the myos repo root on the OS:
# kernel/ and every other directory the Makefile's -I list names (today also
# user/lib/tls/crypto, whose headers the kernel's TLS selftest includes).
#
#   usage: MYOS=/path/to/myos tools/gen-kernel-manifest.sh > kernel.build.ebm
set -eu

. "$(dirname "$0")/hostpaths.sh"
[ -d "$MYOS/kernel" ] || { echo "gen-kernel-manifest: no kernel at $MYOS/kernel" >&2; exit 1; }

# On-OS roots.
OUTDIR=/data/build/out/kernel
EMBCC=/data/apps/embcc/embcc.elf
EMBLD=/data/apps/embld/embld.elf
# embcc's freestanding headers (<stdint.h>, <stddef.h>, ...) ship beside the
# binary; the kernel is freestanding but still includes them, so the compile
# needs this on the include path or on-OS embcc can't find <stdint.h>.
EMBCC_INC=$(dirname "$EMBCC")/include

# Kernel compile flags (myos Makefile CFLAGS, minus gcc-only -ffreestanding/
# -nostdlib which embcc is by nature) and the higher-half link (kernel/linker.ld
# expressed as EmbLD flags: base 0xFFFFFFFF80100000, LMA offset the virtual base;
# the script's .embk_exports table and its __embk_exports_start/_end are EmbLD's
# orphan-section grouping, which needs no flag).
# The include directories are the OS Makefile's own (its CFLAGS -I list, e.g.
# -Ikernel -Iuser/lib/tls/crypto for selftests.c), read below once we are in
# $MYOS — hard-coding `-I<kernel>` alone missed a header outside the kernel
# tree. Each repo-relative dir is /data/src/<dir> on the OS.
CFLAGS_BASE="-mno-red-zone -mno-mmx -mno-sse -mno-sse2 -mcmodel=kernel -O2"
LDFLAGS="-e _start -Ttext 0xFFFFFFFF80100000 --lma-offset 0xFFFFFFFF80000000"

# The 6 hand-written .asm linked into the kernel image (ELF objects; the flat
# boot stages are a separate, -f bin concern outside KM1).
ASMS="kernel/arch/x86_64/irq/isr.asm
      kernel/arch/x86_64/syscall/syscall_entry.asm
      kernel/arch/x86_64/cpu/kcontext.asm
      kernel/arch/x86_64/cpu/kentry.asm
      kernel/arch/x86_64/smp/ap_entry.asm
      kernel/arch/x86_64/smp/ap_trampoline_blob.asm"

# kernel/foo/bar.c -> foo_bar_c.o (kernel/ dropped, / and the extension-dot ->
# _). Keeping the extension distinguishes a .c from a same-named .asm (isr.c vs
# isr.asm), which otherwise collide on the object name.
objname() { o=${1#kernel/}; echo "$(echo "$o" | tr './' '__').o"; }

cd "$MYOS"
SRCS=$(make -p 2>/dev/null | grep '^KERNEL_SRC =' | head -1 | sed 's/KERNEL_SRC = //' \
       | tr ' ' '\n' | grep '\.c$')
INCDIRS=$(make -p 2>/dev/null | grep -E '^CFLAGS :?= ' | head -1 \
          | tr ' ' '\n' | sed -n 's/^-I//p')
[ -n "$INCDIRS" ] || INCDIRS=kernel
HOSTINC=""; OSINC=""
for d in $INCDIRS; do
    HOSTINC="$HOSTINC -I$d"
    OSINC="$OSINC -I/data/src/$d"
done
CFLAGS="$CFLAGS_BASE$OSINC -I$EMBCC_INC"

# Resolve `dir/../` portably (`realpath --relative-to` is GNU-only).
normpath() {
    p=$1
    while :; do
        q=$(printf '%s' "$p" | sed -e 's|/\./|/|g' -e 's|[^/][^/]*/\.\./||')
        [ "$q" = "$p" ] && break
        p=$q
    done
    printf '%s' "$p"
}

printf '# /data/src/kernel/build.ebm -- EmbBuild builds the EmbLinkOS KERNEL (BUILD.md 12).\n'
printf '# GENERATED by EmbCC tools/gen-kernel-manifest.sh -- header closures derived.\n'
printf '# 89 embcc C compiles + 6 embcc .asm assembles + one embld link, no gcc/nasm/ld.\n\n'
printf 'project: kernel\n\n'

cobjs=""
for src in $SRCS; do
    obj=$(objname "$src")
    inputs="/data/src/$src"
    # shellcheck disable=SC2086
    deps=$(cc -MM $HOSTINC "$src" 2>/dev/null | sed 's/^[^:]*://; s/\\//g')
    for d in $deps; do
        [ "$d" = "$src" ] && continue
        d=$(normpath "$d")
        # A repo-relative path is source on the OS; anything absolute is a
        # host artifact of the scan (a system header, macOS's SDKSettings.json).
        case "$d" in /*) : ;; *) inputs="$inputs /data/src/$d" ;; esac
    done
    inputs=$(printf '%s\n' $inputs | awk '!seen[$0]++' | tr '\n' ' ')
    printf 'name: %s\nkind: compile\ninputs: %s\n' "$obj" "$inputs"
    printf 'args: %s -c %s %s/%s -o %s/%s\n' "$EMBCC" "$CFLAGS" /data/src "$src" "$OUTDIR" "$obj"
    printf 'output: %s/%s\n\n' "$OUTDIR" "$obj"
    cobjs="$cobjs $OUTDIR/$obj"
done

aobjs=""
for src in $ASMS; do
    obj=$(objname "$src")
    inputs="/data/src/$src"
    # ap_trampoline_blob.asm incbin's the flat trampoline; list it (staged with
    # the kernel build state). It resolves relative to the build CWD at assemble.
    case "$src" in *ap_trampoline_blob.asm) inputs="$inputs /data/build/ap_trampoline.bin" ;; esac
    printf 'name: %s\nkind: compile\ninputs: %s\n' "$obj" "$inputs"
    printf 'args: %s -c %s/%s -o %s/%s\n' "$EMBCC" /data/src "$src" "$OUTDIR" "$obj"
    printf 'output: %s/%s\n\n' "$OUTDIR" "$obj"
    aobjs="$aobjs $OUTDIR/$obj"
done

printf 'name: kernel.elf\nkind: link\ninputs:%s%s\n' "$cobjs" "$aobjs"
printf 'args: %s %s -o %s/kernel.elf%s%s\n' "$EMBLD" "$LDFLAGS" "$OUTDIR" "$cobjs" "$aobjs"
printf 'output: %s/kernel.elf\n' "$OUTDIR"
