#!/bin/sh
# Regenerate a target's predefined-macro table from the reference compiler.
#
# ARCHITECTURE.md §5: the predefined-macro table is taken from
# `<triple>-gcc -dM -E </dev/null`, never hand-derived. This script is the
# only way those files may change; the generated tables are checked in so
# the build (and eventual self-hosting) does not depend on the cross
# toolchain.
#
# usage: gen-predef.sh [x86_64|aarch64]              regenerate (default: both)
#        gen-predef.sh --reference x86_64|aarch64    print the filtered table
#                                                    (what tests/golden/predef.sh
#                                                    compares --dump-predef with)
#
# Excluded, each for THE RULE (claim only what is present):
#   __GNUC*__, __VERSION__   EmbCC is not gcc; defining these would switch
#                            real headers onto gcc-only extension paths.
#   __STDC*__                owned by the compiler proper, not the target;
#                            cpp defines them itself (see predef.h).
#   __BITINT_MAXWIDTH__      gcc 14+ advertises C23 _BitInt with it; EmbCC
#                            has no _BitInt, so a header testing it must not
#                            be told otherwise.
set -eu

EXCLUDE='^#define (__GNUC|__VERSION__|__STDC|__BITINT_MAXWIDTH__)'

refgcc() {
    gccvar=$(echo "EMBCC_REF_GCC_$1" | tr '[:lower:]' '[:upper:]')
    eval "echo \${$gccvar:-$1-elf-gcc}"
}

reference() {
    "$(refgcc "$1")" -dM -E - </dev/null | LC_ALL=C sort | grep -v -E "$EXCLUDE"
}

# C++ (D-013): the g++ -std=gnu++20 set, less the same families, less every
# macro that CLAIMS a feature EmbCC's C++ does not implement yet — the __cpp_*
# feature tests, exceptions, RTTI, constexpr asm. libstdc++ switches on these,
# so claiming one early would compile code the front-end cannot. A pattern
# leaves this list when its feature lands (docs/CXX.md).
EXCLUDE_CXX='^#define (__GNUG__|__cpp_|__EXCEPTIONS|__GXX_RTTI|__GXX_CONSTEXPR_ASM__)'

refgxx() {
    echo "$(refgcc "$1" | sed 's/gcc$/g++/')"
}

reference_cxx() {
    "$(refgxx "$1")" -std=gnu++20 -x c++ -dM -E - </dev/null | LC_ALL=C sort \
        | grep -v -E "$EXCLUDE" | grep -v -E "$EXCLUDE_CXX"
}

if [ "${1:-}" = --reference ]; then
    reference "${2:?usage: gen-predef.sh --reference x86_64|aarch64}"
    exit 0
fi
if [ "${1:-}" = --reference-cxx ]; then
    reference_cxx "${2:?usage: gen-predef.sh --reference-cxx x86_64|aarch64}"
    exit 0
fi

gen() {
    arch=$1
    GCC=$(refgcc "$arch")
    OUT="$(dirname "$0")/../src/arch/$arch/predef.c"

    command -v "$GCC" >/dev/null 2>&1 || {
        echo "gen-predef: reference compiler '$GCC' not found" >&2
        echo "gen-predef: set $gccvar or add it to PATH" >&2
        exit 1
    }

    {
        echo "/* Generated by tools/gen-predef.sh from \`$("$GCC" -dumpmachine) gcc $("$GCC" -dumpversion) -dM -E\`."
        echo "   Do not edit by hand; rerun the script (ARCHITECTURE.md §5). */"
        echo
        echo "#include \"../predef.h\""
        echo
        echo "const struct predef_macro predef_macros_$arch[] = {"
        reference "$arch" \
            | sed -e 's/^#define \([^ ]*\) \(.*\)$/\1\x01\2/' \
            | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' \
            | sed -e 's/^\(.*\)\x01\(.*\)$/    { "\1", "\2" },/'
        echo "};"
        echo
        echo "const int predef_macro_count_$arch ="
        echo "    (int)(sizeof predef_macros_$arch / sizeof predef_macros_$arch[0]);"
    } > "$OUT"

    echo "gen-predef: wrote $OUT ($(grep -c '{ "' "$OUT") macros)"

    GXX=$(refgxx "$arch")
    OUT="$(dirname "$0")/../src/arch/$arch/predef_cxx.c"
    {
        echo "/* Generated by tools/gen-predef.sh from \`$("$GXX" -dumpmachine) g++ $("$GXX" -dumpversion) -std=gnu++20 -dM -E\`,"
        echo "   less the macros claiming C++ features EmbCC does not implement yet"
        echo "   (EXCLUDE_CXX). Do not edit by hand; rerun the script. */"
        echo
        echo "#include \"../predef.h\""
        echo
        echo "const struct predef_macro predef_macros_cxx_$arch[] = {"
        reference_cxx "$arch" \
            | sed -e 's/^#define \([^ ]*\) \(.*\)$/\1\x01\2/' \
            | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' \
            | sed -e 's/^\(.*\)\x01\(.*\)$/    { "\1", "\2" },/'
        echo "};"
        echo
        echo "const int predef_macro_count_cxx_$arch ="
        echo "    (int)(sizeof predef_macros_cxx_$arch / sizeof predef_macros_cxx_$arch[0]);"
    } > "$OUT"
    echo "gen-predef: wrote $OUT ($(grep -c '{ "' "$OUT") macros)"
}

case "${1:-both}" in
    x86_64)  gen x86_64 ;;
    aarch64) gen aarch64 ;;
    both)    gen x86_64; gen aarch64 ;;
    *) echo "usage: $0 [x86_64|aarch64]" >&2; exit 1 ;;
esac
